import { DataTable } from "mantine-datatable";
import React, { useEffect, useState } from "react";
import { supabase } from "../utils/supabaseClient";

const rc = [
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "aew energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
  {
    product_id: 19,
    shop_id: "d7945c5b-74eb-4af5-be10-9353191cd02a",
    created_at: "2022-11-17T20:33:26.365807+00:00",
    product_name: "New energy",
    product_description: "This is the description bruh",
    product_type: "tshirt",
    product_gender: "Male",
    product_size_available: null,
    product_color: "blue",
    product_material: "cotton",
    product_mrp: 500,
    product_price: 400,
    product_specifications: null,
    product_rating: null,
    product_review_count: null,
    product_brand: "ZARA",
    product_sku: null,
  },
];

export default function DashboardTable({ shopId }) {
  const [productsList, setProductsList] = useState(null);
  const [fetching, setFetching] = useState(false);
  const [page, setPage] = useState(1);
  const [totalRecords, setTotalRecords] = useState(null);

  const PAGE_SIZE = 10;

  useEffect(() => {
    getProductsList(page);
  }, []);

  const setNewPage = async (page) => {
    setPage(page);
    await getProductsList(page);
  };

  const getProductsList = async (page) => {
    try {
      setFetching(true);

      const from = (page - 1) * PAGE_SIZE;
      const to = from + PAGE_SIZE;

      const { data, count } = await supabase
        .from("products")
        .select("*", { count: "exact" })
        .eq("shop_id", shopId)
        .range(from, to);

      setProductsList(data);
      setTotalRecords(count);
    } catch (error) {
      console.log(error);
    } finally {
      setFetching(false);
    }
  };

  return (
    <DataTable
      withBorder
      borderRadius="md"
      shadow="sm"
      withColumnBorders
      highlightOnHover
      horizontalSpacing="sm"
      noRecordsText="No Products to show"
      records={productsList}
      fetching={fetching}
      totalRecords={totalRecords}
      recordsPerPage={PAGE_SIZE}
      page={page}
      onPageChange={(p) => setNewPage(p)}
      columns={[
        {
          accessor: "id",
          title: "#",
          width: 40,
          render: (record) => productsList.indexOf(record) + 1,
        },
        {
          accessor: "product_images",
          title: "Image",
          render: (record) => (
            <img
              src={
                import.meta.env.VITE_PRODUCTIMG_URL + record.product_images[0]
              }
            />
          ),
        },
        { accessor: "product_name", title: "Name" },
        { accessor: "product_brand", title: "Brand" },
        { accessor: "product_type", title: "Type" },
        { accessor: "product_mrp", title: "MRP" },
        { accessor: "product_price", title: "Price" },
      ]}
    />
  );
}
